clc;close all;clear;
load Tainan_no_NE_mat;
Tainan_NE_original{1} = seismic_data{1}(:,[1 3]);
Tainan_NE_original{2} = seismic_data{1}(:,[1 4]);
Tainan_NE_original{3} = seismic_data{2}(:,[1 3]);
Tainan_NE_original{4} = seismic_data{2}(:,[1 4]);
Tainan_NE_original{5} = seismic_data{3}(:,[1 3]);
Tainan_NE_original{6} = seismic_data{3}(:,[1 4]);
Tainan_NE_original{7} = seismic_data{4}(:,[1 3]);
Tainan_NE_original{8} = seismic_data{4}(:,[1 4]);
Tainan_NE_original{9} = seismic_data{5}(:,[1 3]);
Tainan_NE_original{10} = seismic_data{5}(:,[1 4]);
Tainan_NE_original{11} = seismic_data{6}(:,[1 3]);
Tainan_NE_original{12} = seismic_data{6}(:,[1 4]);
Tainan_NE_original{13} = seismic_data{7}(:,[1 3]);
Tainan_NE_original{14} = seismic_data{7}(:,[1 4]);
% Tainan_NE_original{15} = seismic_data{8}(:,[1 3]);
Tainan_NE_original{15} = seismic_data{8}(:,[1 4]);
% Tainan_NE_original{17} = seismic_data{9}(:,[1 3]);
% Tainan_NE_original{18} = seismic_data{9}(:,[1 4]);
% Tainan_NE_original{19} = seismic_data{10}(:,[1 3]);
% Tainan_NE_original{20} = seismic_data{10}(:,[1 4]);
Tainan_NE_original{16} = seismic_data{11}(:,[1 3]);
Tainan_NE_original{17} = seismic_data{11}(:,[1 4]);
Tainan_NE_original{18} = seismic_data{12}(:,[1 3]);
Tainan_NE_original{19} = seismic_data{12}(:,[1 4]);
Tainan_NE_original{20} = seismic_data{13}(:,[1 3]);
Tainan_NE_original{21} = seismic_data{13}(:,[1 4]);
% Tainan_NE_original{22} = seismic_data{14}(:,[1 3]);
% Tainan_NE_original{28} = seismic_data{14}(:,[1 4]);
% Tainan_NE_original{29} = seismic_data{15}(:,[1 3]);
Tainan_NE_original{22} = seismic_data{15}(:,[1 4]);
% save Tainan_NE_original.mat Tainan_NE_original;
 